// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AppDarkModeToggle: typeof import('./src/components/application/AppDarkModeToggle.vue')['default']
    AppLocalePicker: typeof import('./src/components/application/AppLocalePicker.vue')['default']
    AppLogo: typeof import('./src/components/application/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/application/AppProvider.vue')['default']
    AppSearch: typeof import('./src/components/application/search/AppSearch.vue')['default']
    AppSearchFooter: typeof import('./src/components/application/search/AppSearchFooter.vue')['default']
    AppSearchModal: typeof import('./src/components/application/search/AppSearchModal.vue')['default']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    CountdownInput: typeof import('./src/components/countdown/CountdownInput.vue')['default']
    Icon: typeof import('./src/components/icon/Icon.vue')['default']
    QrCode: typeof import('./src/components/qr/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleMenu: typeof import('./src/components/menu/SimpleMenu.vue')['default']
    SimpleSubMenu: typeof import('./src/components/menu/SimpleSubMenu.vue')['default']
    StrengthMeter: typeof import('./src/components/strengthmeter/StrengthMeter.vue')['default']
    SvgIcon: typeof import('./src/components/icon/SvgIcon.vue')['default']
  }
}

export {}
